(* ::Package:: *)

(* ::Input:: *)
(*BeginPackage[ "Trigonometria`"]*)
(*(*ClearAll["Trigonometria`*"];*) *)
(**)
(*EsercizioEsempio::usage = "Stampa un'esercizio d'esempio per calcolare Sen(\[Alpha])";*)
(**)
(*Esercizio1::usage= "Esercizio su seno coseno tangente";*)
(**)
(*Esercizio2::usage = "Esercizio a risposta multipla";*)
(**)
(*Esercizio3::usage = "Esercizio: calcolo lato triangolo - Teorema della corda ";*)
(**)
(*Esercizio4::usage= "Esercizio: trovare lato di un triangolo a risposta multipla";*)
(**)
(*Esercizio5::usage = "Esercizio: trovare il lato C usando la relazione \!\(\*FractionBox[\(\(\\\ \)\(A\)\), \(sen \((\[Alpha])\)\)]\) =\!\(\*FractionBox[\(\(\\\ \)\(B\)\), \(sen \((\[Beta])\)\)]\)";*)
(**)
(*Esercizio6::usage="Esercizio: teorema dei seni risposta multipla";*)
(**)
(*Esercizio7::usage = "Esercizio: trovare il lato C con il teorema del coseno";*)
(**)
(*Esercizio8::usage = "Esercizio: trovare cos(\[Gamma]) usando il teorema del coseno";*)
(**)
(*Esercizio9::usage = "Esercizio: campanile";*)
(**)
(*Esercizio10::usage = "Esercizio: scivolo";*)
(**)
(**)
(*CheckAnswer::usage = "Modulo che compara i parametri answer_ e correct_ passati in input.\n*)
(*                      Il risultato della valutazione \[EGrave] \[Checkmark] se i parametri sono uguali\n*)
(*                      X altrimenti ";*)
(**)
(*Calcolatrice::usage = "Calcolatrice semplice per il calcolo di funzioni trigonometriche";*)
(**)
(*TPitagora::usage = "suggerimento Teorema di pitagora";*)
(**)
(*Begin[ "Private`"]*)
(**)
(**)
(*(*Esercizio d'esempio*)*)
(*EsercizioEsempio[]:=*)
(**)
(*Module[{},*)
(**)
(*datiEsempio = StringJoin[Style["A = 25 \nC = 50",FontFamily-> "sans sarif",Bold],Style["\nTrovare Sen(\[Alpha])",FontColor->Red,FontFamily-> "sans sarif",Bold]];*)
(*risoluzioneEsempio =Panel[" Sin(\[Alpha]) = \!\(\*FractionBox[\(A\), \(B\)]\) = \!\(\*FractionBox[\(\(\\\ \\\ \)\(25\)\(\\\ \)\), \(\(\\\ \)\(50\)\)]\) = \!\(\*FractionBox[\(\(\\\ \)\(1\)\(\\\ \)\), \(2\)]\)"];*)
(**)
(*Grid[{{Text[Style["Esempio 1:",20,FontColor-> Red]]}, *)
(*{Magnify[Graphics[{*)
(*   (* triangle *)*)
(*   Line[{{0, 0}, {0,1}, {2, 0}, {0, 0}}],*)
(*  (* right angle symbol *)*)
(*   Line[{{0, 0.1}, {0.1, 0.1}, {0.1, 0}}],*)
(*  (* angle symbol *)*)
(*  Circle[{2, 0}, 0.2, {145.5 Degree, 182.5 Degree}],*)
(*  Circle[{0,1},0.2,{260 Degree,340 Degree}],*)
(*  (* labels *)*)
(*  Rotate[*)
(*    Text[Style["A", 15],{-0.1, 0.5}], 0 Degree],*)
(*    Text[Style["B", 15],{0.7, -0.1}],*)
(*    Text[Style["C", 15],{1, 0.6}, {-1, 0}],*)
(*    Text[Style["\[Theta]", 10], {1.7, 0.08}],*)
(*    Text[Style["\[Alpha]",10],{0.085,0.75}],*)
(*    Text[Style["90\[Degree]",10],{0.2,0.2}]*)
(*  }],2],*)
(*Magnify[Apply[StringJoin,ToString[#,StandardForm]&/@datiEsempio],1.4],Text[""]},*)
(*{Text[Style["Procedimento:",17,FontColor -> Red]]},{Text[" "],Magnify[risoluzioneEsempio,2]}}*)
(*,Alignment-> {Left,Center},Spacings -> {10,10},Dividers->{{},{3 -> Red}}]*)
(**)
(*]*)
(**)
(*(*Modulo che controlla la correttezza di una risposta data dall'utente*)*)
(*CheckAnswer[answer_,correct_]:=*)
(*DynamicModule[{},*)
(*If[answer == correct,Style["\[Checkmark]",FontColor->Green],Style["X",FontColor->Red,Bold],Text[""]]*)
(*]*)
(**)
(*(*Esercizio1 *)*)
(*Esercizio1[]:=*)
(*Module[{},*)
(*datiEsercizioGuidato = StringJoin[Style["A = 40 \nB = 110",FontFamily-> "sans sarif",Bold],Style["\nTrovare Sen(\[Alpha]),Cos(\[Alpha]),Tan(\[Alpha]) e l'angolo \[Alpha]",FontColor->Red,FontFamily-> "sans sarif",Bold]];*)
(**)
(*risoluzioneEsercizioGuidatoPasso1 = Row[{"Applico la formula \[LongRightArrow] \!\(\*SuperscriptBox[\(A\), \(2\)]\) + ",Dynamic[InputField[Dynamic[catetoNome],String,FieldSize-> 1]],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\) ",Dynamic[CheckAnswer[catetoNome,"B"]]," = ",InputField[Dynamic[ipotenusaNome],String,FieldSize-> 1] ,"\!\(\*SuperscriptBox[\(\\\ \), \(\(2\)\(\\\ \\\ \\\ \)\)]\)",Dynamic[CheckAnswer[ipotenusaNome,"C"]],"\n \n",*)
(*"Sostituisco i valori \[LongRightArrow] \!\(\*SuperscriptBox[\(40\), \(2\)]\) + ",InputField[Dynamic[catetoValore],String,FieldSize-> 3],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\) ",Dynamic[CheckAnswer[catetoValore,"110"]]," = \!\(\*SuperscriptBox[\(C\), \(2\)]\)\n",*)
(*"\n",*)
(*"Ricavo C \[LongRightArrow] C = ",SqrtBox[Row[{"\!\(\*SuperscriptBox[\(A\), \(2\)]\) + ",InputField[Dynamic[catetoBNome],String,FieldSize-> 1],"\!\(\*SuperscriptBox[\(\\\ \), \(\(2\)\(\\\ \\\ \\\ \\\ \)\)]\)"}]] // DisplayForm,Dynamic[CheckAnswer[catetoBNome,"B"]],"\n \n",*)
(*"Approssima il risultato per difetto\n",*)
(*"Calcolo C \[LongRightArrow] C = ", SqrtBox[Row[{InputField[Dynamic[catetoAValore],String,FieldSize-> 2],"\!\(\*SuperscriptBox[\(\\\ \), \(\(2\)\(\\\ \\\ \\\ \\\ \)\)]\)",Dynamic[CheckAnswer[catetoAValore,"40"]]," + ",InputField[Dynamic[catetoBValore],String,FieldSize-> 3],"\!\(\*SuperscriptBox[\(\\\ \), \(\(2\)\(\\\ \\\ \)\)]\)",Dynamic[CheckAnswer[catetoBValore,"110"]]}]] //  DisplayForm," = ",InputField[Dynamic[ipotenusaValore],String,FieldSize->3],Dynamic[CheckAnswer[ipotenusaValore,"117"]]*)
(*}];*)
(**)
(*risoluzioneEsercizioGuidatoPasso2 = Row[{"sen(\[Alpha]) = ",("A")/InputField[Dynamic[ipotenusaSenCNome],String,FieldSize->2],Dynamic[CheckAnswer[ipotenusaSenCNome,"C"]]," = ",("40")/InputField[Dynamic[ipotenusaSenValore],String,FieldSize->3],Dynamic[CheckAnswer[ipotenusaSenValore,"117"]]}];*)
(**)
(*risoluzioneEsercizioGuidatoPasso3 = Row[{"cos(\[Alpha]) = ",("B")/InputField[Dynamic[ipotenusaCosCNome],String,FieldSize->2],Dynamic[CheckAnswer[ipotenusaCosCNome,"C"]]," = ",("110")/InputField[Dynamic[ipotenusaCosValore],String,FieldSize->3],Dynamic[CheckAnswer[ipotenusaCosValore,"117"]]}];*)
(**)
(**)
(*risoluzioneEsercizioGuidatoPasso4 = Row[{"tan(\[Alpha]) = ",Row[{InputField[Dynamic[senNome],String,FieldSize->3],"(\[Alpha])"}]/("cos(\[Alpha])"),Dynamic[CheckAnswer[senNome,"sen"]]," = ",*)
(*Row[{InputField[Dynamic[senValoreNum],String,FieldSize->3],Dynamic[CheckAnswer[senValoreNum,"40"]]}]/Row[ {InputField[Dynamic[senValoreDen],String,FieldSize->3],Dynamic[CheckAnswer[senValoreDen,"117"]]}],"/"*)
(*,*)
(*Row[{InputField[Dynamic[cosValoreNum],String,FieldSize->3],Dynamic[CheckAnswer[cosValoreNum,"110"]]}]/Row[{InputField[Dynamic[cosValoreDen],String,FieldSize->3],Dynamic[CheckAnswer[cosValoreDen,"117"]]}],*)
(*" =\n ",Row[{InputField[Dynamic[senValoreNum2],String,FieldSize->3],Dynamic[CheckAnswer[senValoreNum2,"40"]]}]/Row[ {InputField[Dynamic[senValoreDen2],String,FieldSize->3],Dynamic[CheckAnswer[senValoreDen2,"117"]]}],"\[CenterDot]"*)
(*,*)
(*Row[{InputField[Dynamic[cosValoreNum2],String,FieldSize->3],Dynamic[CheckAnswer[cosValoreNum2,"117"]]}]/Row[{InputField[Dynamic[cosValoreDen2],String,FieldSize->3],Dynamic[CheckAnswer[cosValoreDen2,"110"]]}],*)
(*" = ",*)
(*Row[{InputField[Dynamic[resNum],String,FieldSize->3],Dynamic[CheckAnswer[resNum,"40"]]}]/Row[{InputField[Dynamic[resDen],String,FieldSize->3],Dynamic[CheckAnswer[resDen,"110"]]}]*)
(*,*)
(*" = ",*)
(*Row[{InputField[Dynamic[resNum2],String,FieldSize->3],Dynamic[CheckAnswer[resNum2,"4"]]}]/Row[{InputField[Dynamic[resDen2],String,FieldSize->3],Dynamic[CheckAnswer[resDen2,"11"]]}]*)
(*}];*)
(**)
(*risoluzioneEsercizioGuidatoPasso5 =Row[{"\[Alpha] = \!\(\*SuperscriptBox[\(sen\), \(-1\)]\)(",Row[{InputField[Dynamic[senValoreNum3],String,FieldSize->3],Dynamic[CheckAnswer[senValoreNum3,"40"]]}]/Row[{InputField[Dynamic[*)
(*senValoreDen3],String,FieldSize->3],Dynamic[CheckAnswer[senValoreDen3,"117"]]}],")"}];*)
(**)
(**)
(**)
(*Grid[{{Text[Style["Esercizio guidato:",20,FontColor-> Red]]},*)
(*{Magnify[Graphics[{*)
(*   (* triangle *)*)
(*  Line[{{0, 0}, {0,1}, {2, 0}, {0, 0}}],*)
(*  (* right angle symbol *)*)
(*  Line[{{0, 0.1}, {0.1, 0.1}, {0.1, 0}}],*)
(*  (* angle symbol *)*)
(*  Circle[{2, 0}, 0.2, {145.5 Degree, 182.5 Degree}],*)
(*  Circle[{0,1},0.2,{260 Degree,340 Degree}],*)
(*  (* labels *)*)
(*  Rotate[*)
(*   Text[Style["A", 15],*)
(*    {-0.1, 0.5}], 0 Degree],*)
(*  Text[Style["B", 15],*)
(*   {0.7, -0.1}],*)
(*  Text[Style["C", 15],*)
(*   {1, 0.6}, {-1, 0}],*)
(* Text[Style["\[Alpha]", 10], {1.7, 0.08}],*)
(* Text[Style["\[Beta]",10],{0.085,0.75}],*)
(* Text[Style["90\[Degree]",10],{0.2,0.2}]*)
(*  }],2]*)
(*,Magnify[Apply[StringJoin,ToString[#,StandardForm]&/@datiEsercizioGuidato],1.4],Text[""]},*)
(*{Text[Style["Procedimento:",17,FontColor -> Red]]},*)
(*{Text[Style["Passo 1: cerchiamo l'ipotenusa C.\n Applico il Teorema di Pitagora:",Bold,15]]},*)
(*{Text[""],Panel[Magnify[risoluzioneEsercizioGuidatoPasso1,2]]},*)
(*{Text[Style["Passo 2: cerchiamo sen(\[Alpha]).",Bold,15]]},*)
(*{Text[""],Panel[Magnify[risoluzioneEsercizioGuidatoPasso2,2]]},*)
(*{Text[Style["Passo 3: cerchiamo cos(\[Alpha]).",Bold,15]]},*)
(*{Text[""],Panel[Magnify[risoluzioneEsercizioGuidatoPasso3,2]]},*)
(*{Text[Style["Passo 4: cerchiamo tan(\[Alpha]).",Bold,15]]},*)
(*{Text[""],Panel[Magnify[risoluzioneEsercizioGuidatoPasso4,2]]},*)
(*{Text[Style["Passo 5: cerchiamo \[Alpha].",Bold,15]]},*)
(*{Text[""],Panel[Magnify[risoluzioneEsercizioGuidatoPasso5,2]]}*)
(*},Alignment-> {Left,Center},Spacings -> {10,10}] *)
(**)
(*]*)
(**)
(*(*Esercizio2 Risposta multipla*)*)
(*Esercizio2[]:=*)
(*Module[{},*)
(*datiEsercizio2 = StringJoin[Style["B = 30 \ntan(\[Beta]) = \!\(\*FractionBox[\(3\), \(5\)]\)",FontFamily-> "sans sarif",Bold],Style["\n?A",FontColor->Red,FontFamily-> "sans sarif",Bold]];*)
(**)
(*Grid[{{Text[Style["Esercizio 2:",20,FontColor-> Red]]},*)
(* {Magnify[Graphics[{*)
(*   (* triangle *)*)
(*   Line[{{0, 0}, {0,1.3}, {0.7, 0}, {0, 0}}],*)
(*  (* right angle symbol *)*)
(*   Line[{{0, 0.1}, {0.1, 0.1}, {0.1, 0}}],*)
(*  (* angle symbol *)*)
(**)
(*   Circle[{0,1.3},0.2,{270 Degree,300 Degree}],*)
(*  (* labels *)*)
(*   Rotate[*)
(*       Text[Style["A", 15],*)
(*       {-0.1, 0.5}], 0 Degree],*)
(*       Text[Style["B", 15],*)
(*       {0.3, -0.1}],*)
(*       Text[Style["C", 15],*)
(*       {0.5, 0.6}, {-1, 0}],*)
(*        Text[Style["\[Beta]",10],{0.085,1.0}]*)
(*  }],2],*)
(*Magnify[Apply[StringJoin,ToString[#,StandardForm]&/@datiEsercizio2],1.4]},*)
(**)
(* {Text[Style["Procedimento:",17,FontColor -> Red]]},*)
(**)
(*{Text[Style["Ricorda! tan\[Beta] =\!\(\*FractionBox[\(\(\\\ \)\(cateto\\\ opposto\)\), \(cateto\\\ adiacente\)]\)",Bold,20]]},*)
(**)
(*{Text[Style["Qual \[EGrave] il cateto adiacente?",Bold,20]],Magnify[RadioButtonBar[Dynamic[catAd],{"A","B","C"}],2],Magnify[Dynamic[CheckAnswer[catAd,"A"]],3]},*)
(**)
(*{Text[Style["Qual \[EGrave] il cateto opposto?",Bold,20]],Magnify[RadioButtonBar[Dynamic[catOp],{"A","B","C"}],2],Magnify[Dynamic[CheckAnswer[catOp,"B"]],3]},*)
(**)
(*{Magnify[Row[{Text[Style["tan\[Beta] = "]],Row[{InputField[Dynamic[catOp2],String,FieldSize->1],Dynamic[CheckAnswer[catOp2,"B"]]}]/Row[{InputField[Dynamic[catAd2],String,FieldSize->1],Dynamic[CheckAnswer[catAd2,"A"]]}],Text[Style["\[LongRightArrow] Atan(\[Beta]) = B \[LongRightArrow] A = \!\(\*FractionBox[\(\(\\\ \)\(B\)\), \(tan \((\[Beta])\)\)]\)"]]}],2]},*)
(**)
(*{Text[Style["Quanto vale A??",Bold,20]],Magnify[RadioButtonBar[Dynamic[A],{"50","18","2"}],2],Magnify[Dynamic[CheckAnswer[A,"50"]],3]}*)
(*},Alignment-> {Left,Center},Spacings -> {10,5}] *)
(*]*)
(**)
(*(*Esercizio3 calcolo lato triangolo - Teorema della corda *)*)
(*Esercizio3[]:=*)
(*Module[{},*)
(*pa = {Cos[(Pi/2)+0.3], Sin[(Pi/2)+0.3]};*)
(*pb = {Cos[0-0.2], Sin[0-0.2]};*)
(*pc = {Cos[Pi+0.5], Sin[Pi+0.5]};*)
(**)
(**)
(*Grid[{{Text[Style["Esercizio 3:",20,FontColor-> Red]]},*)
(*{Graphics[{*)
(**)
(*(* CIRCONFERENZA *)*)
(*{Lighter[Gray,0.5],Circle[{0,0},1]},*)
(**)
(*{Darker[Green,0.2],Thick,Circle[{Cos[Pi+0.4], Sin[Pi+0.5]},0.2,{0,1}]},*)
(**)
(*(* TRIANGOLO *)*)
(*{Opacity[0],Black ,EdgeForm[Black], Triangle[{{Cos[(Pi/2)+0.3], Sin[(Pi/2)+0.3]},{Cos[0-0.2], Sin[0-0.2]},{Cos[Pi+0.5], Sin[Pi+0.5]}}]},*)
(**)
(*(* RAGGIO *)*)
(*{Black,Line[{{0,0},{Cos[0-0.2], Sin[0-0.2]}}]},*)
(**)
(*(* CORDA *)*)
(*{Red,Thick,Line[{{Cos[(Pi/2)+0.3], Sin[(Pi/2)+0.3]},{Cos[0-0.2], Sin[0-0.2]}}]},*)
(**)
(*{Black,Disk[{0, 0},0.02]},*)
(*(* PUNTI *)*)
(*(* A *)*)
(*{Black,Disk[{Cos[(Pi/2)+0.3], Sin[(Pi/2)+0.3]},0.02]},*)
(*(* B *)*)
(*{Black,Disk[{Cos[0-0.2], Sin[0-0.2]},0.02]},*)
(*(* C *)*)
(*{Black,Disk[{Cos[Pi+0.5], Sin[Pi+0.5]},0.02]},*)
(**)
(*(* TESTO *)*)
(*Text["  A",{Cos[(Pi/2)+0.4], Sin[(Pi/2)]}],*)
(*Text["   B",{Cos[0], Sin[0-0.3]}],*)
(*Text["   C",{Cos[Pi+0.2], Sin[Pi+0.6]}],*)
(*Text["\!\(\*SuperscriptBox[\(60\), \(o\)]\)",{Cos[Pi+0.9],Sin[11/6 Pi+0.2]}],*)
(*Text["2",{0.4,-0.15}]*)
(**)
(*},PlotRange->1,ImageSize-> 400,BaseStyle->{15},Axes->False,PlotRangePadding->0.25]*)
(**)
(*,Magnify[Style["?AB",FontColor->Red,FontFamily-> "sans sarif",Bold],2]},*)
(*{Text[Style["Procedimento:",17,FontColor -> Red]]},*)
(*{Magnify[Row[{Text[Style["AB = 2\[CenterDot] "]],Row[{InputField[Dynamic[raggio],String,FieldSize->1],Dynamic[CheckAnswer[raggio,"2"]]}]," \[CenterDot] sen(",Row[{InputField[Dynamic[angolo],String,FieldSize->1],"\!\(\*SuperscriptBox[\(\\\ \), \(o\)]\)",Dynamic[CheckAnswer[angolo,"60"]]}],") = ",Row[{InputField[Dynamic[AB],String,FieldSize->1],Dynamic[CheckAnswer[AB,"4"]]}],"\[CenterDot]",Row[{SqrtBox[InputField[Dynamic[num],String,FieldSize->1]]// DisplayForm,Dynamic[CheckAnswer[num,"3"]]}] /Row[{InputField[Dynamic[den],String,FieldSize->1],Dynamic[CheckAnswer[den,"2"]]}]," = ",*)
(*Row[{InputField[Dynamic[coef],String,FieldSize->1],Dynamic[CheckAnswer[coef,"2"]]}]," \[CenterDot]",Row[{SqrtBox[InputField[Dynamic[coef2],String,FieldSize->1]]// DisplayForm,Dynamic[CheckAnswer[coef2,"3"]]}]*)
(*}],2]}*)
(*},Alignment-> {Left,Center},Spacings -> {10,5}] *)
(*]*)
(**)
(*(*Esercizio4*)*)
(*Esercizio4[]:=*)
(*Module[{},*)
(*pa = {Cos[(Pi/2)+0.3], Sin[(Pi/2)+0.3]};*)
(*pb = {Cos[0-0.2], Sin[0-0.2]};*)
(*pc = {Cos[Pi+0.5], Sin[Pi+0.5]};*)
(**)
(**)
(*Grid[{{Text[Style["Esercizio 4:",20,FontColor-> Red]]},*)
(*{Graphics[{*)
(**)
(*(* CIRCONFERENZA *)*)
(*{Lighter[Gray,0.5],Circle[{0,0},1]},*)
(**)
(*{Darker[Green,0.2],Thick,Circle[{Cos[Pi+0.4], Sin[Pi+0.5]},0.2,{0,1}]},*)
(**)
(*(* TRIANGOLO *)*)
(*{Opacity[0],Black ,EdgeForm[Black], Triangle[{{Cos[(Pi/2)+0.3], Sin[(Pi/2)+0.3]},{Cos[0-0.2], Sin[0-0.2]},{Cos[Pi+0.5], Sin[Pi+0.5]}}]},*)
(**)
(*(* RAGGIO *)*)
(*{Black,Line[{{0,0},{Cos[0-0.2], Sin[0-0.2]}}]},*)
(**)
(*(* CORDA *)*)
(*{Red,Thick,Line[{{Cos[(Pi/2)+0.3], Sin[(Pi/2)+0.3]},{Cos[0-0.2], Sin[0-0.2]}}]},*)
(**)
(*{Black,Disk[{0, 0},0.02]},*)
(*(* PUNTI *)*)
(*(* A *)*)
(*{Black,Disk[{Cos[(Pi/2)+0.3], Sin[(Pi/2)+0.3]},0.02]},*)
(*(* B *)*)
(*{Black,Disk[{Cos[0-0.2], Sin[0-0.2]},0.02]},*)
(*(* C *)*)
(*{Black,Disk[{Cos[Pi+0.5], Sin[Pi+0.5]},0.02]},*)
(**)
(*(* TESTO *)*)
(*Text["  A",{Cos[(Pi/2)+0.4], Sin[(Pi/2)]}],*)
(*Text["   B",{Cos[0], Sin[0-0.3]}],*)
(*Text["   C",{Cos[Pi+0.2], Sin[Pi+0.6]}],*)
(*Text["\!\(\*SuperscriptBox[\(60\), \(o\)]\)",{Cos[Pi+0.9],Sin[11/6 Pi+0.2]}],*)
(*Text["5",{0.4,-0.15}]*)
(**)
(*},PlotRange->1,ImageSize-> 400,BaseStyle->{15},Axes->False,PlotRangePadding->0.25]*)
(**)
(*,Magnify[Style["?AB",FontColor->Red,FontFamily-> "sans sarif",Bold],2],Text[""]},*)
(*{Text[Style["Procedimento:",17,FontColor -> Red]]},*)
(*{Magnify[RadioButtonBar[Dynamic[AB2],{"\!\(\*FractionBox[\(5\), \(2\)]\)","\!\(\*FractionBox[\(5\), \(2\)]\)\!\(\*SqrtBox[\(3\)]\)","5","30"}],2],Magnify[Dynamic[CheckAnswer[AB2,"5"]],3]}*)
(**)
(*},Alignment-> {Left,Center},Spacings -> {10,5}] *)
(*]*)
(**)
(**)
(*Esercizio8[]:=*)
(*Module[{},*)
(*datiEsercizio8 = StringJoin[Style["A = 24 \nC = 12\!\(\*SqrtBox[\(3\)]\)\nB = 12",FontFamily-> "sans sarif",Bold],Style["\n?cos(\[Gamma])",FontColor->Red,FontFamily-> "sans sarif",Bold]];*)
(**)
(**)
(*Grid[{{Text[Style["Esercizio 8:",20,FontColor-> Red]]},*)
(*{Magnify[Graphics[{*)
(*   (* triangle *)*)
(*  Line[{{-0.2, 0}, {-0.5,1}, {1, 0}, {-0.2, 0}}],*)
(**)
(*  (* angle symbol *)*)
(**)
(* Circle[{1,0},0.1,{142 Degree,180Degree}],*)
(*  (* labels *)*)
(*  Rotate[*)
(*   Text[Style["C", 10],*)
(*    {-0.4, 0.4}], 0 Degree],*)
(*  Text[Style["A", 10],*)
(*   {0.3, -0.1}],*)
(*  Text[Style["B", 10],*)
(*   {0.2, 0.6}, {-0.4, 0}],*)
(*Text[Style["\[Gamma]",10],{0.8,0.05}]*)
(*  }],2]*)
(*,Magnify[Apply[StringJoin,ToString[#,StandardForm]&/@datiEsercizio8],1.4],Text[""]},*)
(*{Text[Style["Procedimento:",17,FontColor -> Red]]},*)
(*{Text[Style["Ricordati! \!\(\*SuperscriptBox[\(C\), \(2\)]\) = \!\(\*SuperscriptBox[\(B\), \(2\)]\) + \!\(\*SuperscriptBox[\(A\), \(2\)]\) - 2AB cos(\[Gamma])",Bold,20]]},*)
(*{Magnify[Row[{"cos(\[Gamma]) = \!\(\*FractionBox[\(\(\\\ \)\(\*SuperscriptBox[\(B\), \(2\)]\\\  + \\\ \*SuperscriptBox[\(A\), \(2\)]\\\  - \\\ \*SuperscriptBox[\(C\), \(2\)]\)\), \(2  AB\)]\) = ",Row[{InputField[Dynamic[val13],String,FieldSize->2],CheckAnswer[val13,"12"],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\) + 576 - 472"}]/Row[{"2 ", InputField[Dynamic[val14],String,FieldSize->2],CheckAnswer[val14,"288"]}]}],2]},*)
(*{Magnify[Row[{RadioButtonBar[Dynamic[res5],{"\!\(\*FractionBox[\(1\), \(2\)]\)","\!\(\*FractionBox[SqrtBox[\(3\)], \(2\)]\)","-\!\(\*FractionBox[\(1\), \(2\)]\)","-\!\(\*FractionBox[SqrtBox[\(3\)], \(2\)]\)"}],"         ",Dynamic[CheckAnswer[res5,"\!\(\*FractionBox[\(1\), \(2\)]\)"]]}],2]}*)
(**)
(**)
(*},Alignment->{Left,Center},Spacings -> {10,5}]]*)
(**)
(**)
(*(*Esercizio 5*)*)
(*Esercizio5[] := *)
(*Module[{},*)
(**)
(*datiEsercizio5 = StringJoin[Style["A = 6 \n\[Alpha] = \!\(\*SuperscriptBox[\(30\), \(o\)]\)\n\[Beta] = \!\(\*SuperscriptBox[\(105\), \(o\)]\)",FontFamily-> "sans sarif",Bold],Style["\n?C",FontColor->Red,FontFamily-> "sans sarif",Bold]];*)
(**)
(**)
(**)
(*Grid[{{Text[Style["Esercizio 5:",20,FontColor-> Red]]},*)
(*{Magnify[Graphics[{*)
(*   (* triangle *)*)
(*  Line[{{0, 0}, {-1,1}, {0.7, 0}, {0, 0}}],*)
(**)
(*  (* angle symbol *)*)
(**)
(*  Circle[{-1,1},0.2,{310 Degree,340 Degree}],*)
(*Circle[{0,0},0.09,{0 Degree,135 Degree}],*)
(*  (* labels *)*)
(*  Rotate[*)
(*   Text[Style["C", 10],*)
(*    {-0.6, 0.4}], 0 Degree],*)
(*  Text[Style["A", 10],*)
(*   {0.3, -0.1}],*)
(*  Text[Style["B", 10],*)
(*   {0.1, 0.6}, {-0.5, 0}],*)
(* Text[Style["\[Alpha]",10],{-0.8,1.0}],*)
(*Text[Style["\[Beta]",10],{0.1,0.1}]*)
(*  }],2]*)
(*,Magnify[Apply[StringJoin,ToString[#,StandardForm]&/@datiEsercizio5],1.4],Text[""]},*)
(*{Text[Style["Procedimento:",17,FontColor -> Red]]},*)
(*{Magnify[Row[{Text[Style["Calcolare l'ampiezza dell'angolo \[Gamma]:\!\(\*SuperscriptBox[\(180\), \(o\)]\)-("]],InputField[Dynamic[ott],String,FieldSize->3],Style["\!\(\*SuperscriptBox[\(\\\ \), \(o\)]\)"],Dynamic[CheckAnswer[ott,"105"]],Style["+"],InputField[Dynamic[al],String,FieldSize->2],"\!\(\*SuperscriptBox[\(\\\ \), \(o\)]\)",Dynamic[CheckAnswer[al,"30"]],Style[") = "],InputField[Dynamic[res2],String,FieldSize->2],Dynamic[CheckAnswer[res2,"45"]],Style["\!\(\*SuperscriptBox[\(\\\ \), \(o\)]\)"]}],1.5],SpanFromLeft},*)
(**)
(*{Magnify[Text[Style["Utilizzare la relazione \!\(\*FractionBox[\(\(A\)\(\\\ \)\), \(sen \((\[Alpha])\)\)]\) =\!\(\*FractionBox[\(\(\\\ \)\(C\)\), \(sen \((\[Gamma])\)\)]\)"]],1.5]},*)
(*{Text[""],Magnify[Row[{"6"/Row[{"sen(",InputField[Dynamic[al2],String,FieldSize->2],"\!\(\*SuperscriptBox[\(\\\ \), \(o\)]\))",Dynamic[CheckAnswer[al2,"30"]]}]," = ",Row[{InputField[Dynamic[c],String,FieldSize->2],Dynamic[CheckAnswer[c,"C"]]}]/("sen(\!\(\*SuperscriptBox[\(45\), \(o\)]\))")," \[LongRightArrow] ", " 6 / ",Row[{InputField[Dynamic[num3],String,FieldSize->1],Dynamic[CheckAnswer[num3,"1"]]}]/Row[{InputField[Dynamic[den3],String,FieldSize->1],Dynamic[CheckAnswer[den3,"2"]]}]," = ",Row[{InputField[Dynamic[num4],String,FieldSize->1],Dynamic[CheckAnswer[num4,"C"]]}]," /\!\(\*FractionBox[\(\(\\\ \)\*SqrtBox[\(2\)]\), \(2\)]\)"}],2]},*)
(*{Magnify[Text[Style["Ricavare:"]],1.5]},*)
(*{Text[""],*)
(*Magnify[Row[{"C = 6",Row[{SqrtBox[InputField[Dynamic[num5],String,FieldSize->1]]//DisplayForm,Dynamic[CheckAnswer[num5,"2"]]}]/Row[{InputField[Dynamic[den5],String,FieldSize->1],Dynamic[CheckAnswer[den5,"2"]]}]," / ",*)
(*Row[{InputField[Dynamic[num6],String,FieldSize->1],Dynamic[CheckAnswer[num6,"1"]]}]/Row[{InputField[Dynamic[den6],String,FieldSize->1],Dynamic[CheckAnswer[den6,"2"]]}]," = ",InputField[Dynamic[res3],String,FieldSize->1],Dynamic[CheckAnswer[res3,"6"]],SqrtBox[Row[{InputField[Dynamic[res4],String,FieldSize->1],Dynamic[CheckAnswer[res4,"2"]]}]] // DisplayForm }]]}*)
(**)
(**)
(**)
(*},Alignment->{Left,Center},Spacings -> {10,5}]*)
(*]*)
(**)
(*(*Esercizio 6*)*)
(*Esercizio6[]:=*)
(*Module[{},*)
(*datiEsercizio6 = StringJoin[Style["\!\(\*FractionBox[\(A\), \(sen \((\[Alpha])\)\)]\) =\!\(\*FractionBox[\(\(B\)\(\\\ \)\), \(sen \((\[Beta])\)\)]\) =\!\(\*FractionBox[\(\(\\\ \)\(C\)\), \(sen \((\[Gamma])\)\)]\)\n\nA = 12 \n\[Alpha] = \!\(\*SuperscriptBox[\(30\), \(o\)]\)\nB = 9",FontFamily-> "sans sarif",Bold],Style["\n?sen(\[Alpha])",FontColor->Red,FontFamily-> "sans sarif",Bold]];*)
(**)
(*Grid[{{Text[Style["Esercizio:",20,FontColor-> Red]]},*)
(*{Magnify[Graphics[{*)
(* (* triangle *)*)
(*  Line[{{0, 0}, {0,1}, {2, 0}, {0, 0}}],*)
(*  (* right angle symbol *)*)
(*  Line[{{0, 0.1}, {0.1, 0.1}, {0.1, 0}}],*)
(*  (* angle symbol *)*)
(*  Circle[{2, 0}, 0.2, {145.5 Degree, 182.5 Degree}],*)
(*  Circle[{0,1},0.2,{260 Degree,340 Degree}],*)
(*  (* labels *)*)
(*  Rotate[*)
(*   Text[Style["B", 15],*)
(*    {-0.1, 0.5}], 0 Degree],*)
(*  Text[Style["C", 15],*)
(*   {0.7, -0.1}],*)
(*  Text[Style["A", 15],*)
(*   {1, 0.6}, {-1, 0}],*)
(* Text[Style["\[Beta]", 10], {1.7, 0.08}],*)
(* Text[Style["\[Gamma]",10],{0.085,0.75}],*)
(* Text[Style["\[Alpha]",10],{0.2,0.2}]*)
(*  }],2]*)
(*,Magnify[Apply[StringJoin,ToString[#,StandardForm]&/@datiEsercizio6],1.4],Text[""]},*)
(*{Text[Style["Procedimento:",17,FontColor -> Red]]},*)
(*{Text[Style["sen(\[Alpha])?",Bold,20]],Magnify[RadioButtonBar[Dynamic[res4],{"\!\(\*FractionBox[\(3\), \(2\)]\)","\!\(\*FractionBox[\(2\), \(3\)]\)","\!\(\*FractionBox[\(2\), \(3\)]\)\!\(\*SqrtBox[\(3\)]\)","\!\(\*FractionBox[\(3\), \(2\)]\)\!\(\*SqrtBox[\(3\)]\)"}],2],Magnify[Dynamic[CheckAnswer[res4,"\!\(\*FractionBox[\(2\), \(3\)]\)"]],3]}*)
(**)
(**)
(**)
(**)
(*},Alignment->{Left,Center},Spacings -> {10,5}]*)
(*]*)
(**)
(*(*Esercizio 7*)*)
(*Esercizio7[] := *)
(*Module[{},*)
(**)
(*datiEsercizio7 = StringJoin[Style["A = 2 \n\[Gamma] = \!\(\*SuperscriptBox[\(60\), \(o\)]\)\nB = 3",FontFamily-> "sans sarif",Bold],Style["\n?C",FontColor->Red,FontFamily-> "sans sarif",Bold]];*)
(**)
(*Grid[{{Text[Style["Esercizio guidato:",20,FontColor-> Red]]},*)
(*{Magnify[Graphics[{*)
(* (* triangle *)*)
(*  Line[{{0, 0}, {0,1}, {2, 0}, {0, 0}}],*)
(*  (* right angle symbol *)*)
(*  Line[{{0, 0.1}, {0.1, 0.1}, {0.1, 0}}],*)
(*  (* angle symbol *)*)
(*  Circle[{2, 0}, 0.2, {145.5 Degree, 182.5 Degree}],*)
(*  Circle[{0,1},0.2,{260 Degree,340 Degree}],*)
(*  (* labels *)*)
(*  Rotate[*)
(*   Text[Style["B", 15],*)
(*    {-0.1, 0.5}], 0 Degree],*)
(*  Text[Style["C", 15],*)
(*   {0.7, -0.1}],*)
(*  Text[Style["A", 15],*)
(*   {1, 0.6}, {-1, 0}],*)
(* Text[Style["\[Beta]", 10], {1.7, 0.08}],*)
(* Text[Style["\[Gamma]",10],{0.085,0.75}],*)
(* Text[Style["\[Alpha]",10],{0.2,0.2}]*)
(*  }],2]*)
(*,Magnify[Apply[StringJoin,ToString[#,StandardForm]&/@datiEsercizio7],1.4],Text[""]},*)
(*{Text[Style["Procedimento:",17,FontColor -> Red]]},*)
(*{Text[Style["Si applica il teorema del coseno:",Bold,20]], Magnify[Row[{"\!\(\*SuperscriptBox[\(C\), \(2\)]\) + ",InputField[Dynamic[A7],String,FieldSize->1],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\)",Dynamic[CheckAnswer[A7,"A"]]," + ",*)
(*InputField[Dynamic[B7],String,FieldSize->1],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\)",Dynamic[CheckAnswer[B7,"B"]]," - 2 \[CenterDot] A \[CenterDot] " ,*)
(*InputField[Dynamic[B8],String,FieldSize->1],Dynamic[CheckAnswer[B8,"B"]]," \[CenterDot] cos(",,*)
(*InputField[Dynamic[G7],String,FieldSize->1],Dynamic[CheckAnswer[G7,"\[Gamma]"]],")" }]]},*)
(*{Text[Style["Quindi:",Bold,20]], Magnify[Row[{"\!\(\*SuperscriptBox[\(C\), \(2\)]\) + ",InputField[Dynamic[Val7],String,FieldSize->1],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\)",Dynamic[CheckAnswer[Val7,"2"]]," + ",*)
(*InputField[Dynamic[Val8],String,FieldSize->1],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\)",Dynamic[CheckAnswer[Val8,"3"]]," - 12 \[CenterDot] " ,*)
(*Row[{InputField[Dynamic[Val9],String,FieldSize->1],Dynamic[CheckAnswer[Val9,"1"]]}]/Row[{InputField[Dynamic[Val11],String,FieldSize->1],Dynamic[CheckAnswer[Val11,"2"]]}]," = ",*)
(*InputField[Dynamic[Val10],String,FieldSize->1],Dynamic[CheckAnswer[Val10,"7"]] }]]},*)
(**)
(*{Text[Style["Da cui: ",Bold,20]],Magnify[Row[{"C = ",SqrtBox[Row[{InputField[Dynamic[Val12],String,FieldSize->1],Dynamic[CheckAnswer[Val12,"7"]]}]]}] // DisplayForm,2]}*)
(**)
(**)
(*},Alignment->{Left,Center},Spacings -> {10,5}]*)
(*]*)
(**)
(*(*Esercizio 9*)*)
(*Esercizio9[]:=*)
(*Module[{},*)
(*esercizio9testo = Text[Style["Sia H l'altezza del campanile",Bold,20]];*)
(*Grid[{{Text[Style["Esercizio 9:",20,FontColor-> Red]]},*)
(*{esercizio9testo},*)
(*         { Magnify[Sharpen[Import["campanile.jpeg"]],5],*)
(*Magnify[*)
(*Row[{Style["?H\n",FontColor->Red],Style["Approssimare il risultato per difetto\n",FontColor->Red,8],"tan(",InputField[Dynamic[tang],String,FieldSize->1],Dynamic[CheckAnswer[tang,"42"]],"\!\(\*SuperscriptBox[\(\\\ \), \(\[Degree]\)]\)) = ", Row[{InputField[Dynamic[altezza],String,FieldSize->1],Dynamic[CheckAnswer[altezza,"H"]]}]/Row[{InputField[Dynamic[base],String,FieldSize->1],Dynamic[CheckAnswer[base,"80"]]}]," \nH = ",Row[{InputField[Dynamic[base2],String,FieldSize->1],Dynamic[CheckAnswer[base2,"80"]]}]," \[CenterDot] tan(",Row[{InputField[Dynamic[altezza2],String,FieldSize->1],Dynamic[CheckAnswer[altezza2,"42"]]}],"\!\(\*SuperscriptBox[\(\\\ \), \(\[Degree]\)]\)) = ",Row[{InputField[Dynamic[altezza3],String,FieldSize->1],Dynamic[CheckAnswer[altezza3,"72"]]}]}],2]}*)
(**)
(*},Alignment->{Left,Center},Spacings -> {10,5}]*)
(*]*)
(**)
(*(*Esercizio 7*)*)
(*Esercizio7[] := *)
(*Module[{},*)
(**)
(*datiEsercizio7 = StringJoin[Style["A = 2 \n\[Gamma] = \!\(\*SuperscriptBox[\(60\), \(o\)]\)\nB = 3",FontFamily-> "sans sarif",Bold],Style["\n?C",FontColor->Red,FontFamily-> "sans sarif",Bold]];*)
(**)
(*Grid[{{Text[Style["Esercizio guidato:",20,FontColor-> Red]]},*)
(*{Magnify[Graphics[{*)
(* (* triangle *)*)
(*  Line[{{0, 0}, {0,1}, {2, 0}, {0, 0}}],*)
(*  (* right angle symbol *)*)
(*  Line[{{0, 0.1}, {0.1, 0.1}, {0.1, 0}}],*)
(*  (* angle symbol *)*)
(*  Circle[{2, 0}, 0.2, {145.5 Degree, 182.5 Degree}],*)
(*  Circle[{0,1},0.2,{260 Degree,340 Degree}],*)
(*  (* labels *)*)
(*  Rotate[*)
(*   Text[Style["B", 15],*)
(*    {-0.1, 0.5}], 0 Degree],*)
(*  Text[Style["C", 15],*)
(*   {0.7, -0.1}],*)
(*  Text[Style["A", 15],*)
(*   {1, 0.6}, {-1, 0}],*)
(* Text[Style["\[Beta]", 10], {1.7, 0.08}],*)
(* Text[Style["\[Gamma]",10],{0.085,0.75}],*)
(* Text[Style["\[Alpha]",10],{0.2,0.2}]*)
(*  }],2]*)
(*,Magnify[Apply[StringJoin,ToString[#,StandardForm]&/@datiEsercizio7],1.4],Text[""]},*)
(*{Text[Style["Procedimento:",17,FontColor -> Red]]},*)
(*{Text[Style["Si applica il teorema del coseno:",Bold,20]], Magnify[Row[{"\!\(\*SuperscriptBox[\(C\), \(2\)]\) + ",InputField[Dynamic[A7],String,FieldSize->1],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\)",Dynamic[CheckAnswer[A7,"A"]]," + ",*)
(*InputField[Dynamic[B7],String,FieldSize->1],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\)",Dynamic[CheckAnswer[B7,"B"]]," - 2 \[CenterDot] A \[CenterDot] " ,*)
(*InputField[Dynamic[B8],String,FieldSize->1],Dynamic[CheckAnswer[B8,"B"]]," \[CenterDot] cos(",,*)
(*InputField[Dynamic[G7],String,FieldSize->1],Dynamic[CheckAnswer[G7,"\[Gamma]"]],")" }]]},*)
(*{Text[Style["Quindi:",Bold,20]], Magnify[Row[{"\!\(\*SuperscriptBox[\(C\), \(2\)]\) + ",InputField[Dynamic[Val7],String,FieldSize->1],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\)",Dynamic[CheckAnswer[Val7,"2"]]," + ",*)
(*InputField[Dynamic[Val8],String,FieldSize->1],"\!\(\*SuperscriptBox[\(\\\ \), \(2\)]\)",Dynamic[CheckAnswer[Val8,"3"]]," - 12 \[CenterDot] " ,*)
(*Row[{InputField[Dynamic[Val9],String,FieldSize->1],Dynamic[CheckAnswer[Val9,"1"]]}]/Row[{InputField[Dynamic[Val11],String,FieldSize->1],Dynamic[CheckAnswer[Val11,"2"]]}]," = ",*)
(*InputField[Dynamic[Val10],String,FieldSize->1],Dynamic[CheckAnswer[Val10,"7"]] }]]},*)
(**)
(*{Text[Style["Da cui: ",Bold,20]],Magnify[Row[{"C = ",SqrtBox[Row[{InputField[Dynamic[Val12],String,FieldSize->1],Dynamic[CheckAnswer[Val12,"7"]]}]]}] // DisplayForm,2]}*)
(**)
(**)
(*},Alignment->{Left,Center},Spacings -> {10,5}]*)
(*]*)
(**)
(*(*Calcolatrice*)*)
(*Calcolatrice[]:=*)
(*Module[{},*)
(*espressione = "";*)
(*CreateDialog[{Magnify[InputField[Dynamic[espressione],String,Alignment->Right,FieldSize-> 17],2],*)
(*             *)
(*                       Grid[{{*)
(*                      Column[{*)
(*                         Row[ {Button[" 1 ", espressione = StringJoin[espressione ,"1"],FrameMargins->7]," ",*)
(*                                 Button[" 2 ",espressione = StringJoin[espressione ,"2"],FrameMargins->7]," ",*)
(*                                 Button[" 3 ",espressione = StringJoin[espressione ,"3"],FrameMargins->7]}],*)
(*                         Row[ {Button[" 4 ",espressione = StringJoin[espressione ,"4"],FrameMargins->7]," ",*)
(*                                 Button[" 5 ",espressione = StringJoin[espressione ,"5"],FrameMargins->7]," ",*)
(*                                 Button[" 6 ",espressione = StringJoin[espressione ,"6"],FrameMargins->7]}],*)
(*                        Row[ {Button[" 7 ",espressione = StringJoin[espressione ,"7"],FrameMargins->7]," ",*)
(*                                 Button[" 8 ",espressione = StringJoin[espressione ,"8"],FrameMargins->7]," ",*)
(*                                 Button[" 9 ",espressione = StringJoin[espressione ,"9"],FrameMargins->7]}],*)
(*                          Row[ {Button[" C ",If[StringLength[espressione]>0,espressione =StringDrop[espressione,-1],espressione = ""],FrameMargins->7]," ",*)
(*                                 Button[" 0 ",espressione = StringJoin[espressione ,"0"],FrameMargins->7]," ",*)
(*                                 Button[" = ",If[StringLength[espressione]>0,{tmp =StandardForm[ ToExpression[espressione]],espressione = ToString[tmp]}],FrameMargins->7]}]}*)
(*                  ]," ",*)
(*                       Column[{*)
(*                                 Button[" + ", espressione = StringJoin[espressione ,"+"],FrameMargins->7],*)
(*                                 Button[" - ",espressione = StringJoin[espressione ,"-"],FrameMargins->7],*)
(*                                 Button[" * ",espressione = StringJoin[espressione ,"*"],FrameMargins->7],*)
(*                                 Button[" / ",espressione = StringJoin[espressione ,"/"],FrameMargins->7]*)
(**)
(*                  },Spacings->0.5],*)
(**)
(*                     Column[{*)
(*                           ,*)
(*                               Button[" sen ",espressione = StringJoin["Sin[",espressione ," Degree]"],FrameMargins->7],*)
(*                              Button[" cos ",espressione = StringJoin["Cos[",espressione ," Degree]"],FrameMargins->7],*)
(*                              Button[" tan ",espressione = StringJoin["Tan[",espressione ," Degree]"],FrameMargins->7],*)
(*                              Button[" \!\(\*SuperscriptBox[\(x\), \(2\)]\) ",espressione = StringJoin[espressione ,"^2"],FrameMargins->7]*)
(**)
(*                 },Spacings-> 0.5],*)
(*   Column[{*)
(*                           ,*)
(*                               Button[" \!\(\*SuperscriptBox[\(sen\), \(-1\)]\) ",espressione = StringJoin["ArcSin[",espressione ,"]"],FrameMargins->7],*)
(*                              Button[" \!\(\*SuperscriptBox[\(cos\), \(-1\)]\) ",espressione = StringJoin["ArcCos[",espressione ,"]"],FrameMargins->7],*)
(*                              Button[" \!\(\*SuperscriptBox[\(tan\), \(-1\)]\) ",espressione = StringJoin["ArcTan[",espressione ,"]"],FrameMargins->7],*)
(*                              Button["\!\(\*SqrtBox[\(\(x\)\(\\\ \)\)]\) ",espressione = StringJoin["Sqrt[",espressione ,"]"],FrameMargins->7]*)
(**)
(*                 },Spacings-> 0.5]*)
(**)
(*                     },*)
(*                      {Button["Clear",espressione = "",FrameMargins -> 7],SpanFromLeft}*)
(*                 *)
(*                 }]*)
(**)
(*}]*)
(*]*)
(**)
(*(*Teorema di pitagora*)*)
(*TPitagora[]:=*)
(*Module[{},*)
(**)
(*CreateDialog[{Style["Teorema di Pitagora",FontSize->14,Bold],*)
(**)
(*Graphics[{*)
(*(*Triangolo*)*)
(*Line[{{0,0},{0,1},{1.5,0},{0,0}}],*)
(*(*Quadrato Cateto 1*)*)
(*{Lighter[Green,0.5],Rectangle[{0,0},{1.5,-1.5}]},*)
(*{Darker[Green,0.5],Line[{{0,0},{1.5,0},{1.5,-1.5},{0,-1.5},{0,0}}]},*)
(*Text[Style["\!\(\*SuperscriptBox[\(A\), \(2\)]\)",Bold,20],{0.8,-0.7}],*)
(*(*Quadrato Cateto 2*)*)
(*{Lighter[Red,0.5],Rectangle[{0,0},{-1,1}]},*)
(*{Red,Line[{{0,0},{-1,0},{-1,1},{0,1},{0,0}}]},*)
(*Text[Style["\!\(\*SuperscriptBox[\(B\), \(2\)]\)",Bold,20],{-0.5,0.5}],*)
(*(*Quadrato ipotenusa*)*)
(*{Lighter[Blue,0.5],Rotate[Rectangle[{0,1},{1.8,-0.8}],Pi/3 -0.06,{0,1}]},*)
(*{Blue,Line[{{0,1},{1.5,0},{2.5,1.5},{1,2.5},{0,1}}]},*)
(*Text[Style["\!\(\*SuperscriptBox[\(C\), \(2\)]\)",Bold,20],{1.3,1.3}]*)
(*}]*)
(**)
(*}]*)
(*]*)
(**)
(*(*Esercizio 10*)*)
(*Esercizio10[]:=*)
(*Module[{},*)
(*esercizio10testo = Text[Style["Trovare l'angolo \[Alpha]",Bold,20]];*)
(*Grid[{{Text[Style["Esercizio 10:",20,FontColor-> Red]]},*)
(*{esercizio10testo},*)
(*         { Magnify[Sharpen[Import["//home//gianluca//Universit\[AGrave]//Magistrale//Matematica_Computazionale//scivolo.jpeg"]],2],*)
(*Magnify[*)
(*Row[{Style["?\[Alpha]\n",FontColor->Red],Style["Approssima il risultato per difetto alla prima cifra decimale\n\n",FontColor->Red,10],Style[""], Row[{InputField[Dynamic[alpha2],String,FieldSize->2],Dynamic[CheckAnswer[alpha2,"2.5"]]}]/("sen(\[Alpha])")," = ",Row[{InputField[Dynamic[gamma3],String,FieldSize->1],Dynamic[CheckAnswer[gamma3,"3" ]]}]/Row[{"sen(",InputField[Dynamic[gamma2],String,FieldSize->1],"\[Degree])",Dynamic[CheckAnswer[gamma2,"60"]]}]," \[LongRightArrow] ",*)
(*"sen(\[Alpha]) = ",Row[{InputField[Dynamic[latob],String,FieldSize->2],Dynamic[CheckAnswer[latob,"2.5"]]}]/Row[{InputField[Dynamic[latoc],String,FieldSize->1],Dynamic[CheckAnswer[latoc,"3"]]}]," \[CenterDot] ",Row[{SqrtBox[InputField[Dynamic[num10],String,FieldSize->1]]//DisplayForm,Dynamic[CheckAnswer[num10,"3"]] }] /Row[{InputField[Dynamic[den10],String,FieldSize->1],Dynamic[CheckAnswer[den10,"2"]]}],*)
(*" = ",Row[{InputField[Dynamic[res10],String,FieldSize->2],Dynamic[CheckAnswer[res10,"0.7"]]}]*)
(**)
(*}],2]}*)
(**)
(*},Alignment->{Left,Center},Spacings -> {10,5}]*)
(*]*)
(*End[]*)
(**)
(*EndPackage[]*)



